/* 속령 이름·대륙 — 지오글 본편에서 가져왔다 (순위표에 ISO 코드 대신 이름을 쓰려고) */
const TERR_COUNTRIES={
  aw:{k:'아루바',e:'Aruba',x:['aruba']},
  cw:{k:'퀴라소',e:'Curacao',x:['curacao','쿠라사오','쿠라카오']},
  gf:{k:'프랑스령 기아나',e:'French Guiana',x:['french guiana','기아나','프랑스령기아나']},
  gg:{k:'채널 제도',e:'Channel Islands',x:['channel islands','채널제도']},
  gp:{k:'과들루프',e:'Guadeloupe',x:['guadeloupe']},
  gu:{k:'괌',e:'Guam',x:['guam']},
  hk:{k:'홍콩',e:'Hong Kong',x:['hong kong','hongkong']},
  mo:{k:'마카오',e:'Macao',x:['macao','macau','마카우']},
  mq:{k:'마르티니크',e:'Martinique',x:['martinique']},
  nc:{k:'누벨칼레도니',e:'New Caledonia',x:['new caledonia','뉴칼레도니아','누벨칼레도니아']},
  pf:{k:'프랑스령 폴리네시아',e:'French Polynesia',x:['french polynesia','폴리네시아','프랑스령폴리네시아']},
  pr:{k:'푸에르토리코',e:'Puerto Rico',x:['puerto rico','푸에르토 리코']},
  re:{k:'레위니옹',e:'Reunion',x:['reunion','réunion','레위니옹섬']},
  vi:{k:'미국령 버진아일랜드',e:'U.S. Virgin Islands',x:['virgin islands','버진아일랜드','미국령버진아일랜드']},
  yt:{k:'마요트',e:'Mayotte',x:['mayotte']},
  as:{k:'아메리칸사모아',e:'American Samoa',x:['american samoa','아메리칸 사모아']},
  ai:{k:'앵귈라',e:'Anguilla',x:['anguilla']},
  bm:{k:'버뮤다',e:'Bermuda',x:['bermuda']},
  bq:{k:'카리브 네덜란드',e:'Caribbean Netherlands',x:['caribbean netherlands','bonaire','보네르']},
  ky:{k:'케이맨 제도',e:'Cayman Islands',x:['cayman islands','케이맨제도']},
  cx:{k:'크리스마스섬',e:'Christmas Island',x:['christmas island']},
  cc:{k:'코코스 제도',e:'Cocos Islands',x:['cocos islands','keeling islands','코코스제도']},
  ck:{k:'쿡 제도',e:'Cook Islands',x:['cook islands','쿡제도']},
  fk:{k:'포클랜드 제도',e:'Falkland Islands',x:['falkland islands','말비나스','포클랜드제도']},
  fo:{k:'페로 제도',e:'Faroe Islands',x:['faroe islands','페로제도']},
  gi:{k:'지브롤터',e:'Gibraltar',x:['gibraltar']},
  gl:{k:'그린란드',e:'Greenland',x:['greenland']},
  im:{k:'맨섬',e:'Isle of Man',x:['isle of man']},
  je:{k:'저지',e:'Jersey',x:['jersey']},
  ms:{k:'몬트세랫',e:'Montserrat',x:['montserrat']},
  nu:{k:'니우에',e:'Niue',x:['niue']},
  nf:{k:'노퍽섬',e:'Norfolk Island',x:['norfolk island']},
  mp:{k:'북마리아나 제도',e:'Northern Mariana Islands',x:['northern mariana islands','북마리아나제도']},
  pn:{k:'핏케언 제도',e:'Pitcairn Islands',x:['pitcairn islands','핏케언제도']},
  bl:{k:'생바르텔레미',e:'Saint Barthélemy',x:['saint barthelemy','st barts','생바르텔레미섬']},
  sh:{k:'세인트헬레나',e:'Saint Helena',x:['saint helena','어센션','트리스탄다쿠냐']},
  mf:{k:'생마르탱',e:'Saint Martin',x:['saint martin']},
  pm:{k:'생피에르 미클롱',e:'Saint Pierre and Miquelon',x:['saint pierre and miquelon','생피에르미클롱']},
  sx:{k:'신트마르턴',e:'Sint Maarten',x:['sint maarten']},
  tk:{k:'토켈라우',e:'Tokelau',x:['tokelau']},
  tc:{k:'터크스 케이커스 제도',e:'Turks and Caicos Islands',x:['turks and caicos islands','터크스케이커스제도']},
  vg:{k:'영국령 버진아일랜드',e:'British Virgin Islands',x:['british virgin islands','bvi','영국령버진아일랜드']},
  wf:{k:'왈리스 푸투나',e:'Wallis and Futuna',x:['wallis and futuna','왈리스푸투나']},
};
const TERR_CONT={aw:'na',cw:'na',gf:'sa',gg:'eu',gp:'na',gu:'oc',hk:'as',mo:'as',mq:'na',nc:'oc',pf:'oc',pr:'na',re:'af',vi:'na',yt:'af',
  as:'oc',ai:'na',bm:'na',bq:'na',ky:'na',cx:'as',cc:'as',ck:'oc',fk:'sa',fo:'eu',gi:'eu',gl:'na',im:'eu',je:'eu',ms:'na',nu:'oc',nf:'oc',mp:'oc',pn:'oc',bl:'na',sh:'af',mf:'na',pm:'na',sx:'na',tk:'oc',tc:'na',vg:'na',wf:'oc'};
